version: '3.8'

services:
  app:
    build: .
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped