"""add_board_name_to_tickets_and_reanalyse_flag_to_history

Revision ID: 0eb876a2c48c
Revises: f321b46dc28b
Create Date: 2025-08-02 21:08:55.269086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eb876a2c48c'
down_revision = 'f321b46dc28b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_analysis_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reanalyse', sa.Boolean(), nullable=True))

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('board_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('board_name')

    with op.batch_alter_table('ticket_analysis_history', schema=None) as batch_op:
        batch_op.drop_column('reanalyse')

    # ### end Alembic commands ###
