"""Ajout de la table analyse

Revision ID: 126cc617c5f6
Revises: 
Create Date: 2025-07-10 17:17:57.985187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '126cc617c5f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyse',
    sa.Column('analyse_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['config.id'], ),
    sa.PrimaryKeyConstraint('analyse_id'),
    sa.UniqueConstraint('reference')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analyse')
    # ### end Alembic commands ###
