"""Ajout du champ trello_ticket_id unique à la table tickets

Revision ID: 1b43c0a97bd5
Revises: 942b5a9cba71
Create Date: 2025-07-14 14:01:16.968744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b43c0a97bd5'
down_revision = '942b5a9cba71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trello_ticket_id', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['trello_ticket_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('trello_ticket_id')

    # ### end Alembic commands ###
