"""Ajout du champ criticality_level a la table tickets

Revision ID: 6b2490d03099
Revises: b2bae3d82abe
Create Date: 2025-07-14 09:30:37.248362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b2490d03099'
down_revision = 'b2bae3d82abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criticality_level', sa.Enum('low', 'medium', 'high', name='criticality_level_enum'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('criticality_level')

    # ### end Alembic commands ###
