"""Suppression du champ config_id de la table analyse

Revision ID: 6bb0e37fb995
Revises: 1b43c0a97bd5
Create Date: 2025-07-14 14:44:20.374292

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6bb0e37fb995'
down_revision = '1b43c0a97bd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyse', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('analyse_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('config_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('analyse_ibfk_1'), 'config', ['config_id'], ['id'])

    # ### end Alembic commands ###
