"""Création initiale des tables

Revision ID: 752cb56afa2e
Revises: 
Create Date: 2025-08-14 09:12:46.549774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '752cb56afa2e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyse',
    sa.Column('analyse_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('reanalyse', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('analyse_id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_data', sa.JSON(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analyse_board',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analyse_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=60), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analyse_id'], ['analyse.analyse_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id_ticket', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analyse_board_id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.String(length=255), nullable=True),
    sa.Column('ticket_metadata', sa.JSON(), nullable=True),
    sa.Column('board_name', sa.String(length=255), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analyse_board_id'], ['analyse_board.id'], ),
    sa.PrimaryKeyConstraint('id_ticket'),
    sa.UniqueConstraint('ticket_id')
    )
    op.create_table('ticket_analysis_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('analyse_id', sa.Integer(), nullable=False),
    sa.Column('analyse_justification', sa.JSON(), nullable=True),
    sa.Column('criticality_level', sa.Enum('low', 'medium', 'high', name='criticality_level_enum'), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analyse_id'], ['analyse.analyse_id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id_ticket'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_analysis_history')
    op.drop_table('tickets')
    op.drop_table('analyse_board')
    op.drop_table('config')
    op.drop_table('analyse')
    # ### end Alembic commands ###
