"""Ajout des champs updatedAt à toutes les tables et platform à analyse_board

Revision ID: 942b5a9cba71
Revises: 6b2490d03099
Create Date: 2025-07-14 13:47:57.084160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '942b5a9cba71'
down_revision = '6b2490d03099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updatedAt', sa.DateTime(), nullable=True))

    with op.batch_alter_table('analyse_board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('updatedAt', sa.DateTime(), nullable=True))

    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updatedAt', sa.DateTime(), nullable=True))

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updatedAt', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('updatedAt')

    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.drop_column('updatedAt')

    with op.batch_alter_table('analyse_board', schema=None) as batch_op:
        batch_op.drop_column('updatedAt')
        batch_op.drop_column('platform')

    with op.batch_alter_table('analyse', schema=None) as batch_op:
        batch_op.drop_column('updatedAt')

    # ### end Alembic commands ###
