"""Ajout de la table analyse_board

Revision ID: 999d021a03e5
Revises: 126cc617c5f6
Create Date: 2025-07-14 08:32:59.068855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '999d021a03e5'
down_revision = '126cc617c5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyse_board',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analyse_id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.String(length=255), nullable=False),
    sa.Column('board_name', sa.String(length=255), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analyse_id'], ['analyse.analyse_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analyse_board')
    # ### end Alembic commands ###
