"""Ajout du champ list_id et list name a la table analyse_board

Revision ID: 9ea3f099dc5d
Revises: 6bb0e37fb995
Create Date: 2025-07-14 15:32:15.696394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ea3f099dc5d'
down_revision = '6bb0e37fb995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyse_board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('list_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('list_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyse_board', schema=None) as batch_op:
        batch_op.drop_column('list_name')
        batch_op.drop_column('list_id')

    # ### end Alembic commands ###
