"""update columnname trello_ticket_id by ticket_id 

Revision ID: 9fd7a253c0ac
Revises: d384407cdd5d
Create Date: 2025-07-31 10:49:18.708625

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9fd7a253c0ac'
down_revision = 'd384407cdd5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_id', sa.String(length=255), nullable=True))
        batch_op.drop_index(batch_op.f('trello_ticket_id'))
        batch_op.create_unique_constraint(None, ['ticket_id'])
        batch_op.drop_column('trello_ticket_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trello_ticket_id', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('trello_ticket_id'), ['trello_ticket_id'], unique=True)
        batch_op.drop_column('ticket_id')

    # ### end Alembic commands ###
