"""move_reanalyse_field_from_ticket_analysis_history_to_analyse

Revision ID: a3bc759671e1
Revises: cf9b8b0475bd
Create Date: 2025-08-05 17:47:44.073442

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a3bc759671e1'
down_revision = 'cf9b8b0475bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First, add the reanalyse column to analyse table
    with op.batch_alter_table('analyse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reanalyse', sa.Boolean(), nullable=False, server_default=sa.text('FALSE')))
    
    # Set default value to False for existing records (though they should already be false due to server_default)
    op.execute("UPDATE analyse SET reanalyse = FALSE WHERE reanalyse IS NULL")

    # Now drop the reanalyse column from ticket_analysis_history
    with op.batch_alter_table('ticket_analysis_history', schema=None) as batch_op:
        batch_op.drop_column('reanalyse')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add reanalyse column back to ticket_analysis_history
    with op.batch_alter_table('ticket_analysis_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reanalyse', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, server_default=sa.text('FALSE')))

    # Remove reanalyse column from analyse
    with op.batch_alter_table('analyse', schema=None) as batch_op:
        batch_op.drop_column('reanalyse')

    # ### end Alembic commands ###
