"""add board_name to tickets and reanalyse flag to history

Revision ID: board_name_reanalyse_001
Revises: d384407cdd5d
Create Date: 2025-08-02 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'board_name_reanalyse_001'
down_revision = 'd384407cdd5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add board_name column to tickets table
    op.add_column('tickets', sa.Column('board_name', sa.String(length=255), nullable=True))
    
    # Add reanalyse column to ticket_analysis_history table
    op.add_column('ticket_analysis_history', sa.Column('reanalyse', sa.Boolean(), nullable=True, default=False))
    
    # Update existing records to set reanalyse=False by default
    op.execute("UPDATE ticket_analysis_history SET reanalyse = FALSE WHERE reanalyse IS NULL")
    
    # Make reanalyse column non-nullable after setting default values
    op.alter_column('ticket_analysis_history', 'reanalyse', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove reanalyse column from ticket_analysis_history table
    op.drop_column('ticket_analysis_history', 'reanalyse')
    
    # Remove board_name column from tickets table
    op.drop_column('tickets', 'board_name')
    # ### end Alembic commands ###
