"""Ajout de la table tickets

Revision ID: b2bae3d82abe
Revises: 999d021a03e5
Create Date: 2025-07-14 09:23:29.508782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2bae3d82abe'
down_revision = '999d021a03e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id_ticket', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analyse_board_id', sa.Integer(), nullable=False),
    sa.Column('ticket_metadata', sa.JSON(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analyse_board_id'], ['analyse_board.id'], ),
    sa.PrimaryKeyConstraint('id_ticket')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    # ### end Alembic commands ###
