"""add analyse_id to ticket_analysis_history

Revision ID: d384407cdd5d
Revises: f321c63f4528
Create Date: 2025-07-31 10:18:53.926230

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd384407cdd5d'
down_revision = 'f321c63f4528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_analysis_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analyse_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'analyse', ['analyse_id'], ['analyse_id'])
        batch_op.drop_column('user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_analysis_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', mysql.VARCHAR(length=128), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('analyse_id')

    # ### end Alembic commands ###
