"""remove criticality_level from tickets

Revision ID: f321b46dc28b
Revises: 9fd7a253c0ac
Create Date: 2025-07-31 14:59:08.573888

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f321b46dc28b'
down_revision = '9fd7a253c0ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('criticality_level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criticality_level', mysql.ENUM('low', 'medium', 'high'), nullable=True))

    # ### end Alembic commands ###
