"""add ticket_analysis_history table

Revision ID: f321c63f4528
Revises: 
Create Date: 2025-07-31 10:15:15.798678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f321c63f4528'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_analysis_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('analyse_justification', sa.JSON(), nullable=True),
    sa.Column('criticality_level', sa.Enum('low', 'medium', 'high', name='criticality_level_enum'), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('user', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id_ticket'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_analysis_history')
    # ### end Alembic commands ###
